seed: 0
output_dir: '/lgsl_data/checkpoint' # path to save checkpoint and strategy
load_checkpoint: '' # '/lgsl_data/checkpoint/checkpoint'
load_ckpt_format: 'safetensors'  # format of checkpoint files to load
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If True, auto transform `load_checkpoint` to load in distributed model
only_save_strategy: False
resume_training: False # True #'deepseekv3_rank_0_6-1400_1.safetensors'
transform_process_num: 1024
use_parallel: True
run_mode: 'train'
remove_redundancy: True
train_precision_sync: False

monitor_config:
  monitor_on: True
  dump_path: '/lgsl_data/log/dump'
  invert: False
  step_interval: 1
  device_local_loss_format: [ 'log' ]
  device_local_norm_format: [ 'log' ]
  optimizer_state_format: null
  weight_state_format: null
  throughput_baseline: null
  print_struct: False

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'deepseekV3'

# runner config
runner_config:
  epochs: 15
  batch_size: &bs 4
  sink_mode: True
  sink_size: 1

# optimizer
optimizer:
  type: AdamW
  betas: [0.9, 0.95]
  eps: 1.e-8
  weight_decay: 0.1

grouped_lr_schedule:
  default:
    type: ConstantWarmUpLR
    learning_rate: 2.5e-4
#    lr_end: 1e-5
    warmup_steps: 500
    total_steps: 150000
  grouped:
    - type: ConstantWarmUpLR
      params: ['embedding.*', 'output_layer.weight']
      learning_rate: 2.8e-4
      #    lr_end: 1e-5
      warmup_steps: 500
      total_steps: 150000

# dataset
train_dataset: &train_dataset
  data_loader:
    type: OrderedIndexDataLoader
    data_path: "/data01/nlp/bin/M1.1.0"
    cache_dir: "/data01/nlp/k8s_tasks_liuxz/train_1119B_formal/cache"
    shuffle: False
    sequence_length: 4096
    reset_position_ids: False
    eod_mask_loss: False
    create_attention_mask: False
    create_compressed_eod_mask: False
    compressed_eod_mask_length: 128
    eod_token: 2
    pad_token: 3

  input_columns: ["input_ids", "labels", "loss_mask", "position_ids"]
  construct_args_key: ["input_ids", "labels"]

  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset

# mindspore context init config
context:
  mode: 0 # 0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  max_call_depth: 10000
  max_device_memory: "54GB"
  memory_optimize_level: "O0"
  mempool_block_size: "54GB"
  save_graphs: False
  save_graphs_path: "/lgsl_data/checkpoint/graphs"
  jit_config:
    jit_level: "O1" # "O1"
  ascend_config:
    parallel_speed_up_json_path: "/lgsl_data/dianxin_telechat/parallel_speed_up_64M.json"  # 修改此项为数据集并行通信配置路径
  affinity_cpu_list:  False # 绑核

# parallel config for device num = 8
parallel_config:
  data_parallel: &dp 32 # 64
  model_parallel: 8 #8 #4
  pipeline_stage: 4
  expert_parallel: 32 # 64
  micro_batch_num: &micro_batch_num 32 
  vocab_emb_dp: False
  use_seq_parallel: True
  gradient_aggregation_group: 4
# when model parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

# parallel context config
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  enable_alltoall: True
  full_batch: False
  dataset_strategy: [[*dp, 1], [*dp, 1], [*dp, 1], [*dp, 1]]
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  pipeline_config:
    pipeline_interleave: True
    pipeline_scheduler: seqpipe #seqsmartvpp
  strategy_ckpt_config:
    save_file: "./ckpt_strategy.ckpt"
    only_trainable_params: False
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64
    optimizer_weight_shard_size: 512

# recompute config
recompute_config:
  recompute: False # [[3,3,3,2,2,2,2,2], [3,2,2,2,2,2,2,0]] # True
  select_recompute: False
  parallel_optimizer_comm_recompute: True
  mp_comm_recompute: True

# model config
use_legacy: False
model:
  model_config:
    model_type: "deepseek_v3"
    input_sliced_sig: True
    architectures: ["DeepseekV3ForCausalLM"]
    batch_size: *bs  # add for increase predict
    # offset: [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, -2]] # pp8 vpp2
    offset: [[1, 1, 1, 1], [1, 1, 1, -2]]
    pp_interleave_num: 2

    vocab_size: 131072
    seq_length: 4096
    hidden_size: 5120 # 7168
    intermediate_size: 12288 
    num_hidden_layers: &num_layers 53 
    max_position_embeddings: 4096
    hidden_act: 'fusedswiglu'
    num_attention_heads: 128 
    rms_norm_eps: 1.e-5
    add_bias_linear: False
    use_flash_attention: True
    use_attn_mask_compression: True

    multi_latent_attention: True
    mla_qkv_concat: False
    kv_lora_rank: 512
    q_lora_rank: 1536
    qk_rope_head_dim: 64
    v_head_dim: 128
    qk_nope_head_dim: 128
    qk_layernorm: True

    attention_dropout: 0.0
    hidden_dropout: 0.0

    params_dtype: "float32"
    compute_dtype: "bfloat16"
    layernorm_compute_dtype: "float32"
    softmax_compute_dtype: "float32"
    rotary_dtype: "float32"
    router_dense_type: "float32"
    fp32_residual_connection: True
    initializer_range: 0.0048

    num_nextn_predict_layers: &mtp_depth 1
    mtp_loss_factor: 0.2

    position_embedding_type: "rope"
    rotary_scaling_factor: 1
    beta_fast: 32
    beta_slow: 1
    mscale: 1
    mscale_all_dim: 1
    rope_theta: 10000.0
    apply_rope_fusion: False
    bias_swiglu_fusion: False

    # moe config
    gated_linear_unit: True
    moe_intermediate_size: 2048
    routed_scaling_factor: 2.8
    first_k_dense_replace: 1
    n_routed_experts: &expert_num 256 
    num_experts_per_tok: 8
    n_shared_experts: 1
    moe_shared_expert_intermediate_size: 2048
    norm_topk_prob: True
    scoring_func: 'sigmoid'
    moe_grouped_gemm: True
    use_fused_ops_topkrouter: True
    topk_group: 0
    n_group: 0
    moe_z_loss_coeff: 0.0
    use_pad_tokens: False 
    moe_token_dispatcher_type: "alltoall_deredundency"
    moe_router_force_expert_balance: True 
    npu_nums_per_device: 8

    moe_router_load_balancing_type: 'seq_aux_loss'
    moe_aux_loss_coeff: 0.001

    moe_token_drop_policy: False
    moe_router_enable_expert_bias: &moe_router_enable_expert_bias True
    moe_router_bias_update_rate: &moe_router_bias_update_rate 0.001

# callbacks
callbacks:
  - type: MFLossMonitor
    per_print_times: 1
#     wandb_config:
#       key: &wandb_key "local-a99a6d19c648a3448e69973c1b704ee1aff3948a"
#       host: &wandb_host "http://10.127.28.206:1180"
#       project: &wandb_proj "TeleChat-moe"
#       name: &wandb_name "TeleChat-1119B-moe-pretrain"
#       id: &wandb_id "2025-1111-liuxz-1119b-0002"
#       resume: &wandb_resume "allow"
#   # balance topk bias with callback
#   - type: TopkBiasBalanceCallback
#     balance_via_topk_bias: *moe_router_enable_expert_bias
#     topk_bias_update_rate: *moe_router_bias_update_rate
#     expert_num: *expert_num
#     micro_batch_num: *micro_batch_num
#     target_layers: [1,2,30,31,60,61]
#    wandb_config:
#      key: *wandb_key
#      host: *wandb_host
#      project: *wandb_proj
#      name: *wandb_name
#      id: *wandb_id
#      resume: *wandb_resume
#   - type: CheckpointMonitor
#     prefix: "deepseekv3"
#     save_checkpoint_steps: 200
#     keep_checkpoint_max: 1000
#     integrated_save: False
#     remove_redundancy: True
#     async_save: False
#     checkpoint_format: "safetensors"  # format of checkpoint files to save
  - type: TrainCallBack
    stop_step: 30



# wrapper cell config
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense: 1.0
  max_grad_norm: 1.0
  use_clip_grad: True

profile: False
profile_start_step: 1000
profile_stop_step: 1000
init_start_profile: True
profile_communication: False
profile_memory: False
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256
profiler_level: 1
